### ISSUE TITLE
Rika is drawn on top of Rena in Day 4

### ISSUE THREAD

**Issue by miere43** [07th-mod/tsumihoroboshi#47] opened 2020-11-02 21:06 UTC
Happens consistently. Rena is supposed to fade out with Shion, as far as I understood.

_tsum_004.txt, around line 455. I tried to figure out how to fix it, but I couldn't 😕. 

Latest version, Windows.

![image](https://user-images.githubusercontent.com/3995549/97919040-2cc75f80-1d68-11eb-83fb-faf08cff83b2.png)
![yyyyy](https://user-images.githubusercontent.com/3995549/97918942-fc7fc100-1d67-11eb-8775-c02cab8fdc79.png)

**Comment by ItaloKnox** [comment] 2020-11-02 22:24
That seems to be a sprite sticking bug. This can't be fixed in the scripts, it's an issue with the lipsync implementation. Next time you see this happen, save the game and upload the save file. I think only Tsumi, Mina and Matsu are still suffering from this bug.

**Comment by miere43** [comment] 2020-11-03 08:16
@ItaloKnox 
save009.dat - first screenshot, save008.dat - second screenshot
Loaded Day 4 from Extras menu and skipped to section with this bug. 
[higurashi06.zip](https://github.com/07th-mod/tsumihoroboshi/files/5479952/higurashi06.zip)

**Comment by ItaloKnox** [comment] 2020-11-03 08:20
Any chance you can check this out @idealpersona?

**Comment by miere43** [comment] 2020-11-03 15:37
I changed first argument of `ModDrawCharacter` from `0` to `5` and it now works. I don't really know what I did, but whatever.

**Comment by orian34** [comment] 2020-11-03 15:47
I closed the PR because it isn't a real fix.

**Comment by drojf** [comment] 2020-11-04 01:00
hmm...I can reproduce this on my computer, even without loading the save file. Were these issues usually reproducible/non-deterministic?

I inserted a CallScript( "_tsum_004" ); my `flow.txt` to get to that scene rather than using the game menu to get there (because I haven't unlocked anything) if that makes any difference. I also have the save files from miere43 in my save folder, but I don't think that makes any difference if I don't load them (they did not include global.dat file so it's a fresh global.dat)

Since I've been editing the .DLL, I can try to have a look at it, although I haven't looked at the lip sync stuff in a very long time. But if it's so reproducible, maybe it's another bug?

**Comment by drojf** [comment] 2020-11-04 01:21
I'm think the issue really is the sprite being drawn on layer 0....It appears `FadeAllBustshots( 200, TRUE );` doesn't always work if you use layer 0 for the sprite (in this particular case)?

Also, this issue happens regardless of lipsync being enabled, so I'm pretty sure it doesn't have to do with lipsync.

I can reproduce it with this code fragment:
```
	ModDrawCharacter(0, 2, "sprite/re2a_warai_a1_", "0", 160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 5, 200, TRUE );
	FadeAllBustshots( 200, TRUE );
	ModDrawCharacter(3, 4, "sprite/sa2a_warai_a1_", "0", -160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 20, 200, FALSE );
	ModDrawCharacter(4, 5, "sprite/ri2_warai_a1_", "0", 160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 10, 200, TRUE );

	OutputLine(NULL, "「ですわよー！」",
		   NULL, "\"That's correct!\"", GetGlobalFlag(GLinemodeSp));
```

**Comment by drojf** [comment] 2020-11-04 01:27
As per here: 

https://github.com/07th-mod/higurashi-assembly/blob/2393805e12f5c4c8fd95140303228ec613ec701a/Assets.Scripts.Core.Buriko/BurikoScriptFile.cs#L1600-L1619

```c#
private BurikoVariable OperationFadeAllBustshots()
{
	SetOperationType("FadeAllBustshots");
	float wait = (float)ReadVariable().IntValue() / 1000f;
	bool flag = ReadVariable().BoolValue();
	MODSystem.instance.modSceneController.MODLipSyncDisableAll();
	if (gameSystem.IsSkipping)
	{
		wait = 0f;
	}
	for (int i = 1; i < 20; i++)
	{
		gameSystem.SceneController.FadeSprite(i, wait, flag);
	}
	if (flag)
	{
		gameSystem.ExecuteActions();
	}
	return BurikoVariable.Null;
}
```
Only sprites on layers 1-19 are cleared.

**Comment by orian34** [comment] 2020-11-04 08:25
Alright, good to know, I'll fix that then.

**Comment by orian34** [comment] 2020-11-04 08:34
https://github.com/07th-mod/tsumihoroboshi/commit/b57232ad5f96e847221aa76cae8cb714723a35b7

This should be fixed now. @drojf  if you can verify, then the issue can be closed, I'll try to see if other very frequent layer issues appeared with the same command

**Comment by drojf** [comment] 2020-11-04 08:52
@orian34 I tested your changes and it does fix it, but I wouldn't want to close this issue yet...

I searched the script and sprites seem to be really often drawn on layer 0, so the chance of this happening often does seem quite high.

I would like to understand why/how this works:

- Is it a bug that FadeAllBustshots() doesn't clear sprites all layers? 
- Are you not supposed to use layer 0 to draw sprites?
- Why do we use layer 0 to draw sprites? Is it because we run out of other layers to draw sprites on?
- Does the base game draw sprites on layer 0?
- Is there something special about layer 0 as compared to the other layers?

I don't really have any background on this since I don't look at the Higurashi scripts very often

**Comment by orian34** [comment] 2020-11-04 09:08
Right, here's everything I know:
Before reaching the answer arcs, we only used layers 1,2 and 3 for sprites, but after that, it switched to 0,1 and 2, I think I still changed the layer for meakashi, but after that I gave up as it felt more like I didn't want to accept the change and it was way too much work to handle manually.

Layer 0 shouldn't be anything special, and there's no reason not to use it, it's a matter of choice, except it seems that some methods don't count it? Although I don't recall having any layering issues when working on the patch.

Since the layer change originated from the base game, I complied after some effort and now used it as a 4th layer to make better transitioning for heavy layer scenes.

**Comment by drojf** [comment] 2020-11-04 09:13
If we detect in a given script file, layer 4 is never used, can we safely bump all the layer numbers by 1 and have everything still work?

**Comment by orian34** [comment] 2020-11-04 09:16
It'd be better to just switch layer 0 for layer 4, but that should be good? Need to be careful not to miss all the calls for it, I fear this is going to break some stuff, especially for animations

**Comment by miere43** [comment] 2020-11-04 09:57
I played all chapters (1-8) with this mod and voice matching = 0 and this is the only place this bug happens. There was similar bug in chapter 8 but it wasn't reproducible.

**Comment by drojf** [comment] 2020-11-04 09:58
hmmmmmmmmmmmmmmmmmmmm well....I guess...we could just fix it for this one case, and make sure anyone who edits the scripts knows about this issue so they don't accidentally cause it :S

**Comment by drojf** [comment] 2020-11-04 10:00
If you're absolutely certain you didn't see any other reproducible ones, then this would have the least chance of breaking anything

**Comment by miere43** [comment] 2020-11-04 10:02
Yeah, I think it's better to just change layer in this script only instead of changing everything and potentially breaking already playtested game.

**Comment by orian34** [comment] 2020-11-04 10:11
That would make sense then yeah.
Also, just in case, but never use layer 5 for sprites, it's the most commonly used layer for non sprite effects

**Comment by miere43** [comment] 2020-11-04 13:40
Checked https://github.com/07th-mod/tsumihoroboshi/commit/8e8ffa019f14d403a74502e8a45f8916f4614a7b, now everything works correctly (played through full day).

**Comment by orian34** [comment] 2020-11-04 14:31
Alright, thanks. Do open new issues if it still happens somewhere else.

I'll close this one now

**Closed by orian34** 2020-11-04 14:31 UTC
